import express from 'express';
import {randomBytes,createHash} from 'node:crypto';
import {getBoot,gameweek,standings,warm} from './fpl-data.js';
const app=express();app.use(express.json({limit:'1mb'}));app.use(express.static('public'));
const SUPA='https://gjkivetatcnskoszsdzf.supabase.co',SUPA_KEY='sb_publishable_x-etGDngNtgDlY4d4gJsXg_FrbplfY2',ROUTE_CACHE=new Map(),AUTH_ATTEMPTS=new Map();
async function rpc(name,body={}){const r=await fetch(SUPA+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:SUPA_KEY,Authorization:'Bearer '+SUPA_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!r.ok){const msg=(data&&typeof data==='object'&&(data.message||data.error||data.hint))||'Database request failed.';throw Error(String(msg))}return data}
async function cachedRoute(key,ttl,fn){const now=Date.now(),old=ROUTE_CACHE.get(key);if(old&&now-old.at<ttl)return old.data;const data=await fn();ROUTE_CACHE.set(key,{data,at:now});return data}
function readCookies(req){const out={};for(const part of String(req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i<0)continue;const k=part.slice(0,i).trim(),v=part.slice(i+1).trim();if(k)out[k]=decodeURIComponent(v)}return out}const hashToken=t=>createHash('sha256').update(t).digest('hex');function tokenHash(req){const t=readCookies(req).fx_session;return t?hashToken(t):null}function setSession(res,t){res.setHeader('Set-Cookie',`fx_session=${encodeURIComponent(t)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=2592000`)}function clearSession(res){res.setHeader('Set-Cookie','fx_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0')}
function authRate(req,res,next){const ip=String(req.headers['x-forwarded-for']||req.ip||'unknown').split(',')[0].trim(),now=Date.now(),windowMs=600000,max=12,old=AUTH_ATTEMPTS.get(ip);if(!old||now-old.start>windowMs){AUTH_ATTEMPTS.set(ip,{start:now,count:1});return next()}old.count++;if(old.count>max)return res.status(429).json({error:'Too many login attempts. Try again in a few minutes.'});next()}
async function currentUser(req){const h=tokenHash(req);if(!h)return null;try{const rows=await rpc('fx_me',{p_token_hash:h});return Array.isArray(rows)?rows[0]||null:null}catch{return null}}async function requireUser(req,res){const u=await currentUser(req);if(!u){res.status(401).json({error:'Not signed in.'});return null}return u}
app.get('/api/health',async(req,res)=>{try{await rpc('fx_public_profiles',{});res.json({ok:true,app:'FantasyX',accountDb:'connected',auth:'username-password'})}catch{res.status(503).json({ok:false,app:'FantasyX',accountDb:'error'})}});
app.post('/api/auth/signup',authRate,async(req,res)=>{try{const username=String(req.body?.username||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!/^[a-z0-9_]{3,24}$/.test(username))return res.status(400).json({error:'Username must be 3–24 characters using letters, numbers or _.'});if(password.length<8||password.length>72)return res.status(400).json({error:'Password must be 8–72 characters.'});const token=randomBytes(32).toString('hex'),rows=await rpc('fx_signup',{p_username:username,p_password:password,p_token_hash:hashToken(token)}),user=Array.isArray(rows)?rows[0]:null;if(!user)throw Error('Could not create account.');setSession(res,token);res.status(201).json({user})}catch(e){res.status(/already taken/i.test(String(e.message))?409:400).json({error:String(e.message||'Could not create account.')})}});
app.post('/api/auth/login',authRate,async(req,res)=>{try{const username=String(req.body?.username||'').trim().toLowerCase(),password=String(req.body?.password||''),token=randomBytes(32).toString('hex'),rows=await rpc('fx_login',{p_username:username,p_password:password,p_token_hash:hashToken(token)}),user=Array.isArray(rows)?rows[0]:null;if(!user)throw Error('Username or password is incorrect.');setSession(res,token);res.json({user})}catch(e){res.status(/incorrect/i.test(String(e.message))?401:400).json({error:String(e.message||'Could not log in.')})}});
app.post('/api/auth/logout',async(req,res)=>{const h=tokenHash(req);if(h)try{await rpc('fx_logout',{p_token_hash:h})}catch{}clearSession(res);res.json({ok:true})});app.get('/api/auth/me',async(req,res)=>res.json({user:await currentUser(req)}));
app.get('/api/account/profile',async(req,res)=>{try{if(!await requireUser(req,res))return;const rows=await rpc('fx_get_profile',{p_token_hash:tokenHash(req)});res.json({profile:Array.isArray(rows)?rows[0]||null:null})}catch(e){res.status(500).json({error:'Could not load profile.'})}});
app.put('/api/account/profile',async(req,res)=>{try{if(!await requireUser(req,res))return;const rows=await rpc('fx_save_profile',{p_token_hash:tokenHash(req),p_real_name:String(req.body?.real_name||''),p_team_name:String(req.body?.team_name||'My XI')});res.json({profile:Array.isArray(rows)?rows[0]||null:null})}catch(e){res.status(500).json({error:String(e.message||'Could not save profile.')})}});
app.get('/api/account/squad',async(req,res)=>{try{if(!await requireUser(req,res))return;const rows=await rpc('fx_get_squad',{p_token_hash:tokenHash(req)});res.json({squad:Array.isArray(rows)?rows:[]})}catch{res.status(500).json({error:'Could not load squad.'})}});
app.put('/api/account/squad',async(req,res)=>{try{if(!await requireUser(req,res))return;const squad=Array.isArray(req.body?.squad)?req.body.squad.slice(0,15):[];await rpc('fx_save_squad',{p_token_hash:tokenHash(req),p_squad:squad});res.json({ok:true})}catch(e){res.status(500).json({error:String(e.message||'Could not save squad.')})}});
app.post('/api/account/join-league',async(req,res)=>{try{if(!await requireUser(req,res))return;const rows=await rpc('fx_join_league',{p_token_hash:tokenHash(req),p_code:String(req.body?.code||'')}),league=Array.isArray(rows)?rows[0]:null;if(!league)return res.status(404).json({error:'League code not found.'});res.json({league})}catch(e){res.status(/not found/i.test(String(e.message))?404:500).json({error:String(e.message||'Could not join league.')})}});
app.get('/api/players',async(req,res)=>{try{const d=await getBoot(),teams=d.teams.map(t=>({id:t.id,name:t.name,short:t.short_name,code:t.code,badge:`https://resources.premierleague.com/premierleague/badges/70/t${t.code}.png`})),tm=new Map(teams.map(t=>[t.id,t])),types={1:'GK',2:'DEF',3:'MID',4:'FWD'},players=d.elements.filter(p=>p.status!=='u'&&tm.has(p.team)).map(p=>{const t=tm.get(p.team),photoId=String(p.photo||'').replace(/\.jpg$/i,'');return{id:p.id,name:p.web_name,first:p.first_name,second:p.second_name,team:p.team,club:t.short,clubName:t.name,clubBadge:t.badge,pos:types[p.element_type],price:p.now_cost/10,points:0,totalPoints:p.total_points||0,photo:`https://resources.premierleague.com/premierleague/photos/players/250x250/p${photoId}.png`}});res.set('Cache-Control','public,max-age=60');res.json({teams,players})}catch{res.status(502).json({error:'Could not refresh player database.'})}});
app.get('/api/fixtures',async(req,res)=>{try{const gw=Math.max(1,Math.min(38,Number(req.query.gw)||1)),fixtures=await gameweek(gw);res.set('Cache-Control','no-store');res.json({gameweek:gw,gameweeks:Array.from({length:38},(_,i)=>i+1),source:'Randomly generated FantasyX fixtures',fixtures})}catch{res.status(502).json({gameweek:1,fixtures:[]})}});
app.get('/api/football-data',async(req,res)=>{try{const gw=Math.max(1,Math.min(38,Number(req.query.gw)||1)),[fixtures,table]=await Promise.all([gameweek(gw),standings()]);res.set('Cache-Control','no-store');res.json({gameweek:gw,season:'2026/27',fixtures,table,tableSource:'FantasyX completed random fixture results'})}catch{res.status(502).json({gameweek:1,fixtures:[],table:[]})}});
async function liveManagerRows(){const [profiles,squads,boot]=await Promise.all([rpc('fx_public_profiles',{}),rpc('fx_public_squads',{}),getBoot()]),pts=new Map((boot.elements||[]).map(p=>[Number(p.id),Number(p.total_points||0)]));return(profiles||[]).map(p=>{const squad=(squads||[]).filter(s=>s.user_id===p.user_id).map(s=>{const base=pts.get(Number(s.player_id))||0,m=s.is_bench?0:s.is_captain?2:1;return{...s,points:base,scoring_points:base*m,multiplier:m}}),live_points=squad.reduce((n,s)=>n+Number(s.scoring_points||0),0);return{...p,squad,live_points,total_points:live_points}}).sort((a,b)=>b.live_points-a.live_points||String(a.team_name||'').localeCompare(String(b.team_name||''))).map((x,i)=>({...x,rank:i+1}))}
app.get('/api/community',async(req,res)=>{try{const teams=await liveManagerRows();res.set('Cache-Control','no-store');res.json({teams,top_players:[]})}catch{res.status(500).json({teams:[],error:'Community unavailable'})}});
app.get('/api/baller-table',async(req,res)=>{try{const table=await liveManagerRows();res.set('Cache-Control','no-store');res.json({name:'UEFA Baller League',code:'BALLER',live:true,updated_at:new Date().toISOString(),table:table.map(x=>({...x,display_points:x.live_points}))})}catch{res.status(500).json({name:'UEFA Baller League',code:'BALLER',table:[]})}});
app.get('/api/club-table',async(req,res)=>{try{const table=await standings();res.set('Cache-Control','no-store');res.json({season:'2026/27',source:'FantasyX completed random fixture results',table})}catch{res.status(502).json({error:'Club standings unavailable',table:[]})}});
app.use((req,res)=>res.sendFile(process.cwd()+'/public/index.html'));const port=process.env.PORT||3000;app.listen(port,()=>{console.log(`FantasyX listening on ${port}`);warm()});