import express from 'express';import pg from 'pg';const {Pool}=pg;
const app=express();app.use(express.json());app.use(express.static('public'));
const BOOT='https://fantasy.premierleague.com/api/bootstrap-static/';
const SUPA='https://gjkivetatcnskoszsdzf.supabase.co',SUPA_KEY='sb_publishable_x-etGDngNtgDlY4d4gJsXg_FrbplfY2';
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
async function initDb(){if(!pool)return;const sql=[`CREATE TABLE IF NOT EXISTS fantasy_profiles(user_id TEXT PRIMARY KEY,team_name TEXT NOT NULL DEFAULT 'My XI',budget NUMERIC(6,1) NOT NULL DEFAULT 100.0,total_points INTEGER NOT NULL DEFAULT 0,real_name TEXT NOT NULL DEFAULT '',wildcard_used BOOLEAN NOT NULL DEFAULT false,free_hit_used BOOLEAN NOT NULL DEFAULT false,bench_boost_used BOOLEAN NOT NULL DEFAULT false,triple_captain_used BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`,`CREATE TABLE IF NOT EXISTS fantasy_squads(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id TEXT NOT NULL,player_name TEXT NOT NULL,club TEXT NOT NULL,position TEXT NOT NULL,price NUMERIC(5,1) NOT NULL,is_captain BOOLEAN NOT NULL DEFAULT false,is_vice BOOLEAN NOT NULL DEFAULT false,is_bench BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`,`CREATE TABLE IF NOT EXISTS fantasy_leagues(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,code TEXT NOT NULL UNIQUE,owner_user_id TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`,`CREATE TABLE IF NOT EXISTS fantasy_league_members(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),league_id UUID NOT NULL,user_id TEXT NOT NULL,joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(league_id,user_id))`];for(const q of sql)await pool.query(q);await pool.query(`INSERT INTO fantasy_leagues(name,code,owner_user_id) VALUES('UEFA Baller League','BALLER','system') ON CONFLICT(code) DO NOTHING`)}
const sh={apikey:SUPA_KEY,Authorization:'Bearer '+SUPA_KEY};
async function supa(path){const r=await fetch(SUPA+'/rest/v1/'+path,{headers:sh});if(!r.ok)throw Error(await r.text());return r.json()}
app.get('/api/health',async(req,res)=>{let renderDb='not-connected';try{if(pool){await pool.query('SELECT 1');renderDb='connected'}}catch{renderDb='error'}res.json({ok:true,app:'FantasyX',renderDb,supabase:'configured'})});
app.get('/api/players',async(req,res)=>{try{const r=await fetch(BOOT);if(!r.ok)throw Error();const d=await r.json(),teams=d.teams.map(t=>({id:t.id,name:t.name,short:t.short_name})),tm=new Map(teams.map(t=>[t.id,t])),types={1:'GK',2:'DEF',3:'MID',4:'FWD'};const players=d.elements.filter(p=>p.status!=='u'&&tm.has(p.team)).map(p=>{const t=tm.get(p.team),photoId=String(p.photo||'').replace(/\.jpg$/i,'');return{id:p.id,name:p.web_name,first:p.first_name,second:p.second_name,team:p.team,club:t.short,clubName:t.name,pos:types[p.element_type],price:p.now_cost/10,points:0,totalPoints:p.total_points||0,photo:`https://resources.premierleague.com/premierleague/photos/players/250x250/p${photoId}.png`}});res.set('Cache-Control','public,max-age=300');res.json({teams,players})}catch{res.status(502).json({error:'Could not refresh player database.'})}});
function hash(s){return[...s].reduce((a,c)=>a+c.charCodeAt(0),0)}function pairs(a){return Array.from({length:10},(_,i)=>[a[i],a[19-i]])}
app.get('/api/fixtures',async(req,res)=>{try{const d=await(await fetch(BOOT)).json(),clubs=d.teams.map(t=>({id:t.id,name:t.name,short:t.short_name,code:t.code,badge:`https://resources.premierleague.com/premierleague/badges/70/t${t.code}.png`})),rounds=[...clubs],all=[],start=Date.parse('2026-09-16T14:02:00+02:00'),end=Date.parse('2026-09-16T14:30:00+02:00'),now=Date.now(),status=now<start?'Upcoming':now<end?'LIVE':'FT';for(let day=1;day<=10;day++){for(const[home,away]of pairs(rounds)){const i=all.length%10,seed=hash(`D${day}M${i+1}`),final=[seed%4,(seed*7)%3];all.push({id:`D${day}M${i+1}`,home,away,day:`Day ${day}`,time:day===1?'14:02–14:30':'TBD',status:day===1?status:'Upcoming',minute:status==='FT'?90:0,homeScore:day===1&&status==='FT'?final[0]:0,awayScore:day===1&&status==='FT'?final[1]:0,events:[],playerPoints:[],stats:{possession:[50,50],shots:[0,0],shotsOnTarget:[0,0],passes:[0,0],passAccuracy:[0,0],fouls:[0,0],yellowCards:[0,0],redCards:[0,0],offsides:[0,0],corners:[0,0]}})}rounds.splice(1,0,rounds.pop())}res.json({simulation:true,fixtures:all})}catch{res.status(502).json({fixtures:[]})}});
app.get('/api/community',async(req,res)=>{try{const [profiles,squads]=await Promise.all([supa('fantasy_profiles?select=user_id,real_name,team_name,total_points&order=total_points.desc'),supa('fantasy_squads?select=user_id,player_name,club,position,price,is_captain,is_vice,is_bench')]);const teams=profiles.map(p=>({...p,squad:squads.filter(s=>s.user_id===p.user_id).map(s=>({...s,points:0,scoring_points:0,multiplier:s.is_bench?0:s.is_captain?2:1}))}));res.json({teams,top_players:[]})}catch(e){res.status(500).json({teams:[],top_players:[],error:'Community unavailable'})}});
app.get('/api/baller-table',async(req,res)=>{try{const rows=await supa('fantasy_profiles?select=real_name,team_name,total_points&order=total_points.desc,team_name.asc');res.json({name:'UEFA Baller League',code:'BALLER',table:rows.map((x,i)=>({...x,rank:i+1,display_points:x.total_points||0}))})}catch{res.json({name:'UEFA Baller League',code:'BALLER',table:[]})}});
app.use((req,res)=>res.sendFile(process.cwd()+'/public/index.html'));
const port=process.env.PORT||3000;initDb().then(()=>app.listen(port,()=>console.log(`FantasyX listening on ${port}`))).catch(e=>{console.error(e);app.listen(port)});